version: "3.9"  # optional since v1.27.0
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 8080:15672
    volumes:
      - "./data/rabbitmq:/var/lib/rabbitmq/mnesia"
    networks:
      - wonderbill-network

networks:
  wonderbill-network:
    driver: bridge

